version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'crate-ci/typos'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '@types/*'
        update-types: ['version-update:semver-major']
    groups:
      eslint-dependencies:
        patterns:
          - '*eslint*'
