name: 'elm-dependency-submission'
description: 'Send elm dependency snapshot to GitHub API'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'upload'
  color: 'blue'
inputs:
  token:
    description: 'The GITHUB_TOKEN secret'
    required: true
    default: ${{ github.token }}
  elm-json-path:
    description: 'Targeting `elm.json` path. Not elm=tooling.json'
    required: false
    default: 'elm.json'
runs:
  using: 'node20'
  main: 'dist/index.js'
