name: 'elm-dependency-submission'
description: 'Send elm dependency snapshot to GitHub API'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'upload'
  color: 'blue'
inputs:
  token:
    description: 'Basically GITHUB_TOKEN is enough.'
    required: true
  elm-json-path:
    description: 'Targetting `elm.json` path. Not elm=tooling.json'
    required: false
    default: 'elm.json'
runs:
  using: 'node16'
  main: 'dist/index.js'
