name: 'elm-dependency-submission'
description: 'Send dependency information to GitHub in Elm projects'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  token:
    description: 'Basically PAT is needless. Passing GITHUB_TOKEN is enough.'
    required: true
  elm-json-path:
    description: 'Targetting `elm.json` path'
    required: true
    default: 'elm.json'
  dry-run:
    description: 'Avoid http requests for tests'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
