[config]
skip_core_tasks = true

[tasks.setup]
category = "Tools"
description = "Run formatters without changes"
script = [
  "git submodule update --init --recursive",
  "npm install",
]

[tasks.format-check]
category = "Tools"
description = "Run formatters without changes"
script = [
  "dprint check",
]

[tasks.format-apply]
category = "Tools"
description = "Run formatters with changes"
script = [
  "dprint fmt",
]

[tasks.fmt]
alias = "format-apply"

[tasks.typos-check]
category = "Tools"
description = "Run typo checker without changes"
script = [
  "typos . .github .vscode",
]

[tasks.lint-apply]
category = "Tools"
description = "Run linters with changes"
dependencies = [
  # Do not run parallel, because of dprint is superfast and eslint is slow. So sequential makes useful here.
  "format-apply",
]
script = [
  "npm run lint:fix",
]

[tasks.lint-check]
category = "Tools"
description = "Run linters without changes"
dependencies = [
  # Do not run parallel, because of dprint is superfast and eslint is slow. So sequential makes useful here.
  "format-check",
]
script = [
  "npm run lint:check",
]

[tasks.lint]
alias = "lint-check"

[tasks.test-ts]
category = "Tools"
description = 'Test typescripts'
script = [
  "npm test",
]

[tasks.typecheck]
category = "Tools"
description = 'Correctness in TypeScript'
script = [
  "npm run typecheck",
]

[tasks.package]
category = "Tools"
description = 'Correctness in TypeScript'
script = [
  "npm run package",
]

[tasks.check]
category = "Tools"
description = 'Parallel runner for all tests and linters'
run_task = { name = ["typos-check", "test-ts", "typecheck", "lint-check"], parallel = true }

[tasks.all]
category = "Tools"
description = 'Parallel runner for all build, tests and linters'
run_task = { name = ["check", "package"], parallel = true }

[tasks.help]
category = "Tools"
description = 'Might help you - (This one)'
script = [
  'makers --list-category-steps Tools',
]

[tasks.deps]
category = "Tools"
description = 'Print dependency and the versions'
script = [
  "node --version",
  "nix --version",
  "makers --version",
  "dprint --version",
  # Returns NON 0, why...? :<
  # "nixpkgs-fmt --version",
  "typos --version",
  "actionlint --version",
]

[tasks.check_no_git_diff]
category = "Tools"
description = 'This prevents unexpected commit'
script = [
  '(git add --intent-to-add . && git diff --exit-code) || (echo "You should commit all diff before running tests"; exit 1)',
]
