[config]
skip_core_tasks = true

[tasks.setup]
category = "Tools"
description = "Run formatters without changes"
script = [
  "npm install",
]

[tasks.setup-submodule]
category = "Tools"
description = "Run formatters without changes"
script = [
  "git submodule update --init --recursive",
]

[tasks.fmt]
category = "Tools"
description = "Run formatters with changes"
script = [
  "dprint fmt",
]

[tasks.lint]
category = "Tools"
description = "Run linters without changes"
script = [
  "dprint check",
  "deno lint",
  "typos . .github .vscode",
]

[tasks.test]
category = "Tools"
description = 'Test typescripts'
script = [
  "npm test",
]

[tasks.typecheck]
category = "Tools"
description = 'Correctness in TypeScript'
script = [
  "npm run typecheck",
]

[tasks.build]
category = "Tools"
description = 'Build'
script = [
  "npm run build",
]

[tasks.check]
category = "Tools"
description = 'Parallel runner for all tests and linters'
run_task = { name = ["test", "typecheck", "lint", "build"], parallel = true }

[tasks.all]
category = "Tools"
description = 'Parallel runner for all build, tests and linters'
run_task = { name = ["check", "package"], parallel = true }

[tasks.help]
category = "Tools"
description = 'Might help you - (This one)'
script = [
  'makers --list-category-steps Tools',
]

[tasks.deps]
category = "Tools"
description = 'Print dependency and the versions'
script = [
  "node --version",
  "nix --version",
  "makers --version",
  "dprint --version",
  # Returns NON 0, why...? :<
  # "nixpkgs-fmt --version",
  "typos --version",
]

[tasks.check_no_git_diff]
category = "Tools"
description = 'This prevents unexpected commit'
script = [
  '(git add --intent-to-add . && git diff --exit-code) || (echo "You should commit all diff before running tests"; exit 1)',
]
