name: Validate with running on my own
on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/dependabot.yml'
      - 'LICENSE'
      - '.editorconfig'
      - 'dprint.json'
      - 'README.md'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/dependabot.yml'
      - 'LICENSE'
      - '.editorconfig'
      - 'dprint.json'
      - 'README.md'
      - '.vscode/**'

permissions:
  contents: write

jobs:
  validate: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # Fetch example project
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - uses: ./
        with:
          elm-json-path: emobu/elm.json
